version: '3.3'

services:
  zookeeper:
    container_name: test-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: test-kafka
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://test-kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: test_user             # postgres user
      POSTGRES_PASSWORD: test_password # postgres password
    ports:
      - 5432:5432                         # postgres port
    volumes:
      # copy the sql script to create tables
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql:ro